### ISSUE TITLE
The url path is broken, should be /_/ not / on the UI to go to the real admin

### ISSUE THREAD

**Issue by miguelgargallo** [coollabsio/pocketbase#22]
The url path is broken, should be /_/ not / on the UI to go to the real admin

**Comment by orenaksakal** [comment]
@miguelgargallo I can't replicate the issue are you still facing this?

**Comment by miguelgargallo** [comment]
Always when I run as a container Dockerfile directly

**Comment by joelherzog** [comment]
same for me

**Comment by orenaksakal** [comment]
This repo is for coolify's pocketbase template
I use it as template from coolify templates section and works like a charm 

you might need to modify docker commands yourself if you are using it as dockerfile I don't think your problem relates to this repo
