### ISSUE TITLE
How to mount a persistent volume for PocketBase 

### ISSUE THREAD

**Issue by steff-mat** [coollabsio/pocketbase#30]
As I had this issue for quite some time, and it was no so easy to find the fix, it would be good to have the official documentation extended with this info:

Volume Mount

Name
pb-storage

Source Path
[do not complete or if you want to share the pb_data for whatever reason type /app/pb_data]

Destination Path
/app/pb_data

**Comment by orenaksakal** [comment]
@steff-mat the template should already be creating a volume for you

Feel free to open a PR for the documentation change/suggestion 👍
