### ISSUE TITLE
QUESTION: How to get access to pb_data / pb_hook throught Coolify?

### ISSUE THREAD

**Issue by aychernov** [coollabsio/pocketbase#38]
It`s possible or need to deploy from GitHub repo for that?

**Comment by orenaksakal** [comment]
hey you should add your hooks to /pb_hooks folder and it should be named *.pb.js like `main.pb.js `
you can find your docker volumes at `/var/lib/docker/volumes/` from here find the pocketbase app and move to data folder then create a pb_hooks folder and create the js file in it it will be picked up automatically if not you can try restarting the service from dashboard but it works for me
